services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "4004:4004"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - PORT=4004
  db:
    image: postgres:16
    environment:
      - 'POSTGRES_USER=coffee'
      - 'POSTGRES_PASSWORD=secret'
    volumes:
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./docker/pgdata:/var/lib/postgresql/data
    ports:
      - "5436:5436"
